//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursoProfesor
    {
        public int ID_CursoProfesor { get; set; }
        public Nullable<int> ID_Curso { get; set; }
        public Nullable<int> ID_Profesor { get; set; }
        public Nullable<int> Ciclo { get; set; }
        public Nullable<int> Anio { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Profesor Profesor { get; set; }
    }
}
