//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.TI_Web.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURSO
    {
        public int ID_CURSO { get; set; }
        public Nullable<int> ID_PROFESOR { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public string HORARIO { get; set; }
        public Nullable<int> CREDITOS { get; set; }
    
        public virtual PROFESOR PROFESOR { get; set; }
    }
}
