//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using web.TI_Web.modelos;

    public partial class bd_webEntities : DbContext
    {
        public bd_webEntities()
            : base("name=bd_webEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CURSO> CURSOes { get; set; }
        public virtual DbSet<PROFESOR> PROFESORs { get; set; }
    }
}
